### ISSUE TITLE
A small problem with a dataset

### ISSUE THREAD

**Issue by hai8023** [royorel/StyleSDF#8]
When I use the ffhq dataset, how many data do I need? I only downloaded `images1024x1024 `there is a problem with training.
```
Traceback (most recent call last):
  File "/home/haimou/anaconda3/envs/StyleSDF2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/haimou/anaconda3/envs/StyleSDF2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/haimou/anaconda3/envs/StyleSDF2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haimou/anaconda3/envs/StyleSDF2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haimou/Desktop/PyAll/StyleSDF/dataset.py", line 42, in __getitem__
    img = Image.open(buffer)
  File "/home/haimou/anaconda3/envs/StyleSDF2/lib/python3.8/site-packages/PIL/Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f3ac305f310>

```

**Comment by richardburleigh** [comment]
You may need to try the steps in 'Preparing your Dataset' again

**Comment by royorel** [comment]
@hai8023,

As @richardburleigh said, please follow the steps in "Preparing your Dataset" section. It saves the dataset in lmdb format instead of loading each image separately.

**Comment by hai8023** [comment]
I succeeded after getting the latest code，thanks for your help
